### PR TITLE
Add variables for policy extension lists

### PR DESCRIPTION
**Pull request by DEvil0000**

### CODE REVIEW

**Comment by juju4** [comment]
Please keep same default values as existing.

**Comment by DEvil0000** [comment]
are you sure the default values did make more sense - since the differed from the role extension list?

23.01.2021 20:15:01 Julien <notifications@github.com>:

**Comment by juju4** [comment]
change was to add variables, not to change features
and that's not because you want to allow an extension that you always want it.
In existing role, allow and force list are different
Also, extensions are really a thing that should be reviewed before any use as each context will have its own specific, be it users, company clients or servers systems and so on.

If I remember correctly, chrome_extensions was used when installing extension by download+file (old way)

**Comment by DEvil0000** [comment]
Using your exact previous values in defaults now

**Comment by juju4** [comment]
Thanks

**Pull request merged**
